### ISSUE TITLE
childNode selector throws console error

### ISSUE THREAD

**Issue by simonkastenhuber** [roflmuffin/plyr-resolution-selector#2]
First of all: Thanks for the script. Exactly what i was looking for. 
But i needed to change some selectors to make it work. For example:

`player.media.childNodes.length` to `player.media.children.length` 

Unfortunately I have no time for further investigations. Just wanted to let you know :) 

Cheers

**Comment by roflmuffin** [comment]
Hi Simon,

Cheers for the heads up, I'll take a look when I get the chance. I'm glad the script was of use :)
