### ISSUE TITLE
Plugin does not work with plyr > 2.0

### ISSUE THREAD

**Issue by ArdiArtani** [roflmuffin/plyr-resolution-selector#3]
Hello, the plugin is not working?

Needs to be updated.

**Comment by roflmuffin** [comment]
Sorry for the delay Ardi,

The plugin has only been tested on version 1.8.2 at the moment, looking at the [changelog for plyr](https://github.com/Selz/plyr/blob/master/changelog.md) it appears there were some changes in 2.0 that would have broken the plugin.

I'll investigate and get a new version out when I get the chance, but you can use a legacy version of Plyr if you would like to use the plugin.

**Comment by roflmuffin** [comment]
Fixed in eee4db0, plugin should now work with latest version.

**Comment by ArdiArtani** [comment]
Thank you!
